In [1]:
import numpy as np

In [3]:
new = np.arange(7)
n = new.astype(float)
n

array([0., 1., 2., 3., 4., 5., 6.])

In [5]:
n

array([ 0.,  1.,  2.,  3., nan,  5.,  6.])

In [8]:
new[4]=3.4

In [12]:
arr_rand = np.arange(9)

In [13]:
arr_rand

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.where(arr_rand>4,'g4',(np.where(arr_rand==4,'e4','L4')))

array(['L4', 'L4', 'L4', 'L4', 'e4', 'g4', 'g4', 'g4', 'g4'], dtype='<U2')

In [18]:
np.argmax(arr_rand)

8

In [24]:
x = np.zeros([3,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
y = np.ones([3,3])
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
z = np.ones([3,4])
z

TypeError: ones() got an unexpected keyword argument 'axis'

In [37]:
np.concatenate([x,z],axis=1)

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

In [38]:
s = np.random.randint(10,size=[3,3])

In [39]:
s


array([[2, 5, 8],
       [8, 8, 9],
       [8, 2, 2]])

In [42]:
np.sort(s,axis=0)

array([[2, 2, 2],
       [8, 5, 8],
       [8, 8, 9]])

In [43]:
s

array([[2, 5, 8],
       [8, 8, 9],
       [8, 2, 2]])

In [44]:
np.mean(s,axis=0)

array([6.        , 5.        , 6.33333333])

In [64]:
t = np.random.randint(8,size=[3,3])

In [63]:
t

array([[2, 7, 1],
       [2, 4, 2],
       [5, 1, 5]])

In [53]:
t[1,:].argsort()

array([0, 2, 1], dtype=int64)

In [54]:
t

array([[2, 7, 1],
       [2, 4, 2],
       [5, 1, 5]])

In [75]:
np.lexsort((t[:,1],t[:,2]))

array([1, 0, 2], dtype=int64)

In [74]:
t

array([[3, 3, 3],
       [1, 2, 1],
       [6, 4, 6]])

In [72]:
a= np.lexsort((t[:,1],t[:,0]))