In [2]:
import numpy as np
import sys

In [2]:
arr = np.arange(2,10)

In [17]:
a = arr.astype(str)

In [6]:
c = arr+a

In [7]:
c

array([ 4.,  6.,  8., 10., 12., 14., 16., 18.])

In [18]:
a.shape

(8,)

In [13]:
a.ndim

1

In [20]:
a.size

8

In [21]:
arr.itemsize

4

In [29]:
sys.getsizeof('6')

42

In [25]:
sys.getsizeof(123)

28

In [33]:
sys.getsizeof(123.5220)

24

In [32]:
sys.getsizeof({'s':1})

184

In [6]:

# np.random.seed(6)
print(np.random.randint(14,100,size=[2,3]))

[[98 45 80]
 [19 40 29]]


In [21]:
print(np.random.randint(14,100,size=[2,3]))

[[99 25 15]
 [96 49 36]]


In [12]:
a

0.5846312725955531

In [18]:
a = np.random.random()
a

0.043704646608971

In [37]:
data = np.random.randint(0,5, size = (4,3))

In [38]:
data

array([[0, 4, 2],
       [1, 2, 3],
       [4, 4, 0],
       [3, 4, 1]])

In [6]:
data.mean(axis=0)

array([2.5 , 1.75, 1.75])

In [11]:
data[:2,:2]

array([[2, 3],
       [1, 3]])

In [12]:
data[:1,:1]

array([[2]])

In [15]:
data[:,2:] = data[:,2:]+10

In [16]:
data

array([[ 2,  3, 24],
       [ 1,  3, 24],
       [ 1,  1, 20],
       [ 0,  2, 24]])

In [18]:
data[::-2,:]

array([[ 0,  2, 24],
       [ 1,  3, 24]])

In [19]:
data[data>2]

array([ 3, 24,  3, 24, 20, 24])

In [39]:
data

array([[0, 4, 2],
       [1, 2, 3],
       [4, 4, 0],
       [3, 4, 1]])

In [40]:
a = data.flatten()

In [42]:
a[3]=10

In [43]:
data

array([[0, 4, 2],
       [1, 2, 3],
       [4, 4, 0],
       [3, 4, 1]])

In [44]:
a = data.ravel()

In [45]:
a[3]=10

In [46]:
data

array([[ 0,  4,  2],
       [10,  2,  3],
       [ 4,  4,  0],
       [ 3,  4,  1]])